### ISSUE TITLE
Discord server invite link expired

### ISSUE THREAD

**Issue by karsalfrink** [participatoryml/participatoryml.github.io#4]
When I click the link (`https://discord.gg/KSAwXKs`) Discord tells me "invite invalid".

**Comment by bogdan-kulynych** [comment]
Thanks for flagging, Kars! I just checked with someone and checked in the Discord settings, it seems that this link should be valid. Were you able to join yourself?

**Comment by karsalfrink** [comment]
Okay. I bypassed my VPN and now it works. Thanks for getting back to me.
